### ISSUE TITLE
Highgui function not available

### ISSUE THREAD

**Issue by pervez8ktt** [opencv-java/camera-calibration#2]
Hi,
Thanks for your awesome examples
it is really very helpful and appreciable.

I just want to report two issues.

1. please replace

Highgui.imencode(".png", frame, buffer); 
to
Imgcodecs.imencode(".png", frame, buffer);

2. Please change package of VideoCapture.

Thanks again
regards

**Comment by luigidr** [comment]
Hi @pervez8ktt,

this project was made for OpenCV 2.x. I need to update it to OpenCV 3.x and fix those issues, you are absolutely right!
Thank you!
