### ISSUE TITLE
Mixup of Collums and Lines in Chessboard-Detection

### ISSUE THREAD

**Issue by Tynogc** [opencv-java/camera-calibration#4]
Size boardSize = new Size(this.numCornersHor, this.numCornersVer);
https://github.com/opencv-java/camera-calibration/blob/621b7b1fa230c2049a5ee981c05d071e91d1cc1f/src/application/CC_Controller.java#L285

This is most likely the wrong way around, it should mean ...(Ver, Hor); 
It can lead to quite odd behavior, according to this:

"Note If you use a non-square (=non-NxN) grid and findChessboardCorners() for calibration, and calibrateCamera returns bad values (zero distortion coefficients, an image center very far from (w/2-0.5,h/2-0.5), and/or large differences between f_x and f_y (ratios of 10:1 or more)), then you have probably used patternSize=cvSize(rows,cols) instead of using patternSize=cvSize(cols,rows) in findChessboardCorners() ." - From: https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html

**Comment by luigidr** [comment]
You are right, I'm going to commit this change, thanks!
